### ISSUE TITLE
[ENH]: Duecredit integration

### ISSUE THREAD

**Issue by marcelzwiers** [Remi-Gau/bids2cite#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

I have implemented [duecredit](https://github.com/duecredit/duecredit) to generate citation reports. It would be nice if this could be integrated with bids2cite? Or are they both dealing with different problem spaces?

**Comment by Remi-Gau** [comment]
I think the problems that those tools are different.

bids2cite tries to use what's in the `dataset_description.json` to create a standardized file used for citations (datacite or citation.cff)

given that BIDS now officially supports citation.cff I think I will focus on those

**Comment by marcelzwiers** [comment]
Ok, I'll have a look into it

**Comment by Remi-Gau** [comment]
I have been planning to update it for a while. So don't expect anything "wow".
